BitcoreNode:
  NetworkMonitor:
    network: livenet
    host: localhost
    port: 8333
LevelUp: ./db
RPC:
  username: username
  password: password
  protocol: http
  network: livenet
  host: 127.0.0.1
  port: 8332
