BitcoreNode:
  NetworkMonitor:
    network: livenet
    host: localhost
    port: 8333
Reporter: simple # none, simple, matrix
LevelUp: ./db
RPC:
  username: username
  password: password
  protocol: http
  host: 127.0.0.1
  port: 8332
